version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: "redis:alpine"

volumes:
  mongo-data:

networks:
  mynetwork: